-- ============================================================================
-- STICKER SWAP - SUPABASE SCHEMA DESIGN
-- Run this in your Supabase SQL Editor to set up the database tables.
-- ============================================================================

-- 1. ENABLE UUID GENERATION
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. PROFILES TABLE
-- Linked directly to auth.users created through Supabase Auth
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT UNIQUE NOT NULL,
    avatar_url TEXT,
    free_packs_claimed_today INT DEFAULT 0,
    last_free_pack_claimed_at TIMESTAMPTZ,
    coins INT DEFAULT 100,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) for Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profile Policies
DROP POLICY IF EXISTS "Allow public read access to profiles" ON public.profiles;
CREATE POLICY "Allow public read access to profiles" ON public.profiles 
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow users to update their own profile" ON public.profiles;
CREATE POLICY "Allow users to update their own profile" ON public.profiles 
    FOR UPDATE USING (auth.uid() = id);

-- 3. TRIGGER FOR AUTOMATIC PROFILE CREATION ON SIGN UP
-- When a user registers through auth.signUp, a profile row is created automatically
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, username, avatar_url, coins)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
        'https://api.dicebear.com/7.x/bottts/svg?seed=' || new.id,
        100
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 4. TEAMS TABLE (32 World Cup squads)
CREATE TABLE IF NOT EXISTS public.teams (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    country_code VARCHAR(3) UNIQUE NOT NULL, -- e.g., 'ARG', 'BRA', 'POR'
    primary_color TEXT NOT NULL,           -- Hex Code e.g. '#00529B'
    secondary_color TEXT NOT NULL,         -- Hex Code e.g. '#FFFFFF'
    flag_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to teams" ON public.teams;
CREATE POLICY "Allow public read access to teams" ON public.teams 
    FOR SELECT USING (true);

-- 5. PLAYERS (STICKERS) TABLE (576 individual player cards)
CREATE TABLE IF NOT EXISTS public.players (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INT REFERENCES public.teams(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    position VARCHAR(3) NOT NULL,          -- 'GK', 'DF', 'MF', 'FW'
    number INT NOT NULL,                   -- Number within the team (1 to 18)
    rating INT DEFAULT 80,                 -- Player rating (e.g. 70-99)
    is_shiny BOOLEAN DEFAULT FALSE,        -- Special/foil shiny background
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_team_player_number UNIQUE (team_id, number)
);

ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to players" ON public.players;
CREATE POLICY "Allow public read access to players" ON public.players 
    FOR SELECT USING (true);

-- 6. USER COLLECTION TABLE (Inventory of owned stickers)
CREATE TABLE IF NOT EXISTS public.user_collection (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    player_id INT NOT NULL REFERENCES public.players(id) ON DELETE CASCADE,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_player UNIQUE (user_id, player_id)
);

ALTER TABLE public.user_collection ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage their own collection" ON public.user_collection;
CREATE POLICY "Users can manage their own collection" ON public.user_collection 
    FOR ALL USING (auth.uid() = user_id);

-- 7. TRADES TABLE (Peer-to-peer custom trading hub)
CREATE TABLE IF NOT EXISTS public.trades (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    receiver_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL, -- NULL = open to anyone
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled')),
    sender_agreed BOOLEAN DEFAULT FALSE,
    receiver_agreed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.trades ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can see trades they are involved in or open trades" ON public.trades;
CREATE POLICY "Users can see trades they are involved in or open trades" ON public.trades
    FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id OR receiver_id IS NULL);

DROP POLICY IF EXISTS "Users can create trades" ON public.trades;
CREATE POLICY "Users can create trades" ON public.trades 
    FOR INSERT WITH CHECK (auth.uid() = sender_id);

DROP POLICY IF EXISTS "Users can update their trades" ON public.trades;
CREATE POLICY "Users can update their trades" ON public.trades 
    FOR UPDATE USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

-- 8. TRADE ITEMS TABLE (Specific cards swapped in a trade offer)
CREATE TABLE IF NOT EXISTS public.trade_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    trade_id UUID NOT NULL REFERENCES public.trades(id) ON DELETE CASCADE,
    player_id INT NOT NULL REFERENCES public.players(id) ON DELETE CASCADE,
    is_offered BOOLEAN NOT NULL, -- TRUE if offered by sender, FALSE if requested from receiver
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0)
);

ALTER TABLE public.trade_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Access trade items of visible trades" ON public.trade_items;
CREATE POLICY "Access trade items of visible trades" ON public.trade_items
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.trades 
            WHERE trades.id = trade_items.trade_id 
              AND (trades.sender_id = auth.uid() OR trades.receiver_id = auth.uid() OR trades.receiver_id IS NULL)
        )
    );

DROP POLICY IF EXISTS "Users can add items to trades they created" ON public.trade_items;
CREATE POLICY "Users can add items to trades they created" ON public.trade_items
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.trades 
            WHERE trades.id = trade_items.trade_id 
              AND trades.sender_id = auth.uid()
        )
    );

-- ============================================================================
-- 9. RPC FUNCTION: increment_sticker_inventory
-- Called when a user opens a pack. Inserts the sticker into user_collection
-- if not owned yet, or increments quantity if they already have it (duplicate).
-- ============================================================================
CREATE OR REPLACE FUNCTION public.increment_sticker_inventory(
    p_user_id UUID,
    p_player_id INT,
    p_qty INT DEFAULT 1
)
RETURNS VOID AS $$
BEGIN
    INSERT INTO public.user_collection (user_id, player_id, quantity)
    VALUES (p_user_id, p_player_id, p_qty)
    ON CONFLICT (user_id, player_id)
    DO UPDATE SET
        quantity = public.user_collection.quantity + EXCLUDED.quantity,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- 10. RPC FUNCTION: execute_sticker_trade
-- Handles real-time ledger exchange of stickers between sender and receiver.
-- Verifies inventory holds before adjusting quantities in user_collection.
-- ============================================================================
CREATE OR REPLACE FUNCTION public.execute_sticker_trade(
    p_trade_id UUID,
    p_receiver_id UUID
)
RETURNS VOID AS $$
DECLARE
    v_sender_id UUID;
    v_status VARCHAR(20);
    v_item RECORD;
    v_sender_qty INT;
    v_receiver_qty INT;
BEGIN
    -- 1. Lock and retrieve trade details
    SELECT sender_id, status INTO v_sender_id, v_status
    FROM public.trades
    WHERE id = p_trade_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Trade offer not found';
    END IF;

    IF v_status != 'pending' THEN
        RAISE EXCEPTION 'Trade is no longer pending (current status: %)', v_status;
    END IF;

    IF v_sender_id = p_receiver_id THEN
        RAISE EXCEPTION 'Cannot trade with yourself';
    END IF;

    -- 2. Loop through all trade items to validate inventory and perform transfer
    FOR v_item IN 
        SELECT player_id, is_offered, quantity 
        FROM public.trade_items 
        WHERE trade_id = p_trade_id
    LOOP
        IF v_item.is_offered THEN
            -- Sender offers, receiver receives.
            -- Verify sender has enough quantity.
            v_sender_qty := 0; -- Reset before check to handle no-row case
            SELECT quantity INTO v_sender_qty
            FROM public.user_collection
            WHERE user_id = v_sender_id AND player_id = v_item.player_id;

            IF v_sender_qty IS NULL OR v_sender_qty < v_item.quantity THEN
                RAISE EXCEPTION 'Sender does not have enough copies of player id % to complete trade', v_item.player_id;
            END IF;

            -- Deduct from sender
            UPDATE public.user_collection
            SET quantity = quantity - v_item.quantity, updated_at = NOW()
            WHERE user_id = v_sender_id AND player_id = v_item.player_id;

            -- Add to receiver
            INSERT INTO public.user_collection (user_id, player_id, quantity)
            VALUES (p_receiver_id, v_item.player_id, v_item.quantity)
            ON CONFLICT (user_id, player_id)
            DO UPDATE SET 
                quantity = public.user_collection.quantity + EXCLUDED.quantity,
                updated_at = NOW();
        ELSE
            -- Receiver offers, sender receives.
            -- Verify receiver has enough quantity.
            v_receiver_qty := 0; -- Reset before check to handle no-row case
            SELECT quantity INTO v_receiver_qty
            FROM public.user_collection
            WHERE user_id = p_receiver_id AND player_id = v_item.player_id;

            IF v_receiver_qty IS NULL OR v_receiver_qty < v_item.quantity THEN
                RAISE EXCEPTION 'Receiver does not have enough copies of player id % to complete trade', v_item.player_id;
            END IF;

            -- Deduct from receiver
            UPDATE public.user_collection
            SET quantity = quantity - v_item.quantity, updated_at = NOW()
            WHERE user_id = p_receiver_id AND player_id = v_item.player_id;

            -- Add to sender
            INSERT INTO public.user_collection (user_id, player_id, quantity)
            VALUES (v_sender_id, v_item.player_id, v_item.quantity)
            ON CONFLICT (user_id, player_id)
            DO UPDATE SET 
                quantity = public.user_collection.quantity + EXCLUDED.quantity,
                updated_at = NOW();
        END IF;
    END LOOP;

    -- 3. Update trade record header status to accepted and set receiver ID
    UPDATE public.trades
    SET status = 'accepted', receiver_id = p_receiver_id, updated_at = NOW()
    WHERE id = p_trade_id;

    -- Clean up user collections with zero quantity to keep database tidy
    DELETE FROM public.user_collection WHERE quantity = 0;

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- 11. TRADE CHATS TABLE (Real-time message history in a trade room)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.trade_chats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    trade_id UUID NOT NULL REFERENCES public.trades(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) for Trade Chats
ALTER TABLE public.trade_chats ENABLE ROW LEVEL SECURITY;

-- Trade Chats Policies
DROP POLICY IF EXISTS "Access trade chats of visible trades" ON public.trade_chats;
CREATE POLICY "Access trade chats of visible trades" ON public.trade_chats
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.trades 
            WHERE trades.id = trade_chats.trade_id 
              AND (trades.sender_id = auth.uid() OR trades.receiver_id = auth.uid() OR trades.receiver_id IS NULL)
        )
    );

DROP POLICY IF EXISTS "Users can insert messages into trades they are involved in" ON public.trade_chats;
CREATE POLICY "Users can insert messages into trades they are involved in" ON public.trade_chats
    FOR INSERT WITH CHECK (
        auth.uid() = sender_id AND
        EXISTS (
            SELECT 1 FROM public.trades 
            WHERE trades.id = trade_chats.trade_id 
              AND (trades.sender_id = auth.uid() OR trades.receiver_id = auth.uid() OR trades.receiver_id IS NULL)
        )
    );
